### EXPERIMENT 2: Numerical Phyton

DE LEON, Maria Nichole Lexanie C.

In [2]:
import numpy as np

#### **NORMALIZATION PROBLEM**

In [6]:
# Create a random 5x5 ndarray and store it in variable X

X = np.random.rand(5,5)
X

array([[0.76137446, 0.37629812, 0.00384683, 0.27392871, 0.54079038],
       [0.26354101, 0.60446247, 0.52844448, 0.97795409, 0.95704682],
       [0.5289523 , 0.92066875, 0.54864608, 0.36705719, 0.35166064],
       [0.31019546, 0.52028749, 0.92512979, 0.6271112 , 0.3462683 ],
       [0.83292823, 0.22882955, 0.91013858, 0.88391471, 0.93695328]])

In [12]:
# Normalize X

# Obtain element-wise mean and standard deviation
X_mean = X.mean()
X_std = X.std ()
X_normalize = (X - X_mean) / X_std

# Save the normalized ndarray as X_normalized.npy
np.save('X_normalized.npy', X_normalize)

In [14]:
# Print the arrays
print("Original 5x5 ndarray X:\n", X)
print("\nNormalized 5x5 ndarray X_normalized:\n", X_normalize)

Original 5x5 ndarray X:
 [[0.76137446 0.37629812 0.00384683 0.27392871 0.54079038]
 [0.26354101 0.60446247 0.52844448 0.97795409 0.95704682]
 [0.5289523  0.92066875 0.54864608 0.36705719 0.35166064]
 [0.31019546 0.52028749 0.92512979 0.6271112  0.3462683 ]
 [0.83292823 0.22882955 0.91013858 0.88391471 0.93695328]]

Normalized 5x5 ndarray X_normalized:
 [[ 0.65563701 -0.74450761 -2.09874737 -1.11672467 -0.14641075]
 [-1.15449453  0.08510215 -0.19130066  1.44312455  1.36710531]
 [-0.1894542   1.23483401 -0.11784728 -0.77810783 -0.83408995]
 [-0.98485811 -0.22095962  1.25105441  0.16745334 -0.8536966 ]
 [ 0.91580786 -1.28070605  1.1965461   1.10119564  1.29404484]]


#### **DIVISIBLE BY 3 PROBLEM**

In [30]:
# Create a 10x10 ndarray with squares of the first 100 positive int
A = np.arange(1,101)**2
A = A.reshape(10,10)
print (A)

[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [32]:
# Determine all the elements that are divisible by 3
d3 = A[A % 3 == 0]

# Save the ndarray as div_by_3.npy
np.save('div_by_3.npy', d3)

In [40]:
# Print the ndarray
print("ndarray A:\n", A)
print("\nElements divisible by 3:\n", d3)

ndarray A:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
